package mc.duzo.timeless.client.animation.player;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class TimelessPlayerAnimations {
    public static final Animation MK5_CASE_OPEN = Animation.Builder.create(8.04f)
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.88f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.24f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.32f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.84f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.88f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.24f, AnimationHelper.createRotationalVector(60f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.32f, AnimationHelper.createRotationalVector(62.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.84f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.24f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.56f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.24f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.12f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.88f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.24f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.32f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.84f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.88f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.24f, AnimationHelper.createRotationalVector(60f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.32f, AnimationHelper.createRotationalVector(62.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.84f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.88f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.24f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.32f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.84f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.88f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.24f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.8f, AnimationHelper.createRotationalVector(-81.16f, -3.14f, 21.4f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.92f, AnimationHelper.createRotationalVector(-75f, 0f, 27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.36f, AnimationHelper.createRotationalVector(0f, 52.5f, 70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.72f, AnimationHelper.createRotationalVector(0f, 52.5f, 70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.24f, AnimationHelper.createRotationalVector(0f, 20f, 27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.44f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0.88f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.76f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0.88f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.24f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.32f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.84f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0.88f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.24f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.8f, AnimationHelper.createRotationalVector(-81.16f, 3.14f, -21.4f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(1.92f, AnimationHelper.createRotationalVector(-75f, 0f, -27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.36f, AnimationHelper.createRotationalVector(0f, -52.5f, -70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.72f, AnimationHelper.createRotationalVector(0f, -52.5f, -70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(3.24f, AnimationHelper.createRotationalVector(0f, -20f, -27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(8.44f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0.88f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.76f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.8f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR))).build();

    public static final Animation MK5_CASE_CLOSE = Animation.Builder.create(8.04f)
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(6.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.119999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.199999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(1.3199999999999994f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(2.1999999999999993f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(4.879999999999999f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.199999999999999f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.119999999999999f, AnimationHelper.createRotationalVector(62.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.199999999999999f, AnimationHelper.createRotationalVector(60f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(8.44f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(6.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.119999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.199999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -10f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(6.6f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.119999999999999f, AnimationHelper.createRotationalVector(62.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.199999999999999f, AnimationHelper.createRotationalVector(60f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(8.44f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(6.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.119999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.199999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.199999999999999f, AnimationHelper.createRotationalVector(0f, 20f, 27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.719999999999999f, AnimationHelper.createRotationalVector(0f, 52.5f, 70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.08f, AnimationHelper.createRotationalVector(0f, 52.5f, 70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.52f, AnimationHelper.createRotationalVector(-75f, 0f, 27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.64f, AnimationHelper.createRotationalVector(-81.16f, -3.14f, 21.4f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.199999999999999f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.4399999999999995f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.56f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("right_arm",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(6.64f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.68f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(6.6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.119999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.199999999999999f, AnimationHelper.createTranslationalVector(0f, -6f, -8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.199999999999999f, AnimationHelper.createRotationalVector(0f, -20f, -27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(5.719999999999999f, AnimationHelper.createRotationalVector(0f, -52.5f, -70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.08f, AnimationHelper.createRotationalVector(0f, -52.5f, -70f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.52f, AnimationHelper.createRotationalVector(-75f, 0f, -27.5f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(6.64f, AnimationHelper.createRotationalVector(-81.16f, 3.14f, -21.4f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.199999999999999f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.4399999999999995f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC),
                            new Keyframe(7.56f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.CUBIC)))
            .addBoneAnimation("left_arm",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(6.64f, AnimationHelper.createScalingVector(0.99f, 0.99f, 0.99f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.68f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.56f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR))).build();
}
